version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests ....
          command: npm run test
      - run:
          name: Build app....
          command: npm run build

  deploy:
    executor: node/default
    steps:
      - run:
          name: deploy only on merge
          command: docker build . -tag my-app

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
