version: 2.1

orbs:
  node: circleci/node@14
  docker: circleci/docker@20

jobs:
  install_packages:
    executor: node
    steps:
      - checkout
      - run:
          command: |
            npm install
  build_docker:
    executor: docker
    steps:
      - checkout
      - run:
          command: |
            docker build . -t my-node-app -f Dockerfile

workflows:
  test_pr:
    jobs:
      - install_packages
      - build_docker:
          requires:
            - install_packages
          filters:
            branches:
              only: master
